name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: CI


jobs:

  format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      
      - name: Check formatting
        run: |
          clang-format -n -Werror -style=file -i src/*.{cpp,hpp} tests/*.cpp

  # unit-tests:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
    
  #   - name: Configure CMake
  #     run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} # -DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE

  #   - name: Build
  #     run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  #   - name: Run tests
  #     working-directory: ${{github.workspace}}/build
  #     run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
